sky-fire.vbs|vbscript|UTF-8|album|http://comic.sky-fire.com/HTML/?*
sky-fire.vbs|vbscript|UTF-8|album|http://comic.sfacg.com/HTML/?*
sky-fire.vbs|vbscript|UTF-8|photo|http://*pic*.sky-fire.com/AllComic/?*
sky-fire.vbs|vbscript|UTF-8|photo|http://*pic*.sfacg.com/AllComic/?*
imouto.vbs|vbscript|UTF-8|photo|http://yande.re/*
imouto.vbs|vbscript|UTF-8|photo|https://yande.re/*
ggyy8.vbs|vbscript|UTF-8|photo|http://www.ggyy8.?*/html/?*/?*.html*
ggyy8.vbs|vbscript|UTF-8|album|http://www.ggyy8.?*/html/?*.html
donmai_us.vbs|vbscript|UTF-8|photo|http://?*.donmai.us/*
163blog.vbs|vbscript|GB2312|photo|http://?*.blog.163.com/?*?albumId=?*
163blog.vbs|vbscript|GB2312|photo|http://blog.163.com/?*/?*?albumId=?*
163blog.vbs|vbscript|GB2312|photo|http://?*.blog.163.com/?*?aId=?*
163blog.vbs|vbscript|GB2312|photo|http://blog.163.com/?*/?*?aId=?*
163blog.vbs|vbscript|GB2312|photo|http://s*.ph*.1*.???/?*.js
163blog.vbs|vbscript|GB2312|album|http://*.blog.163.com/*
163blog.vbs|vbscript|GB2312|album|http://blog.163.com/?*
pixiv.vbs|vbscript|UTF-8|photo|http://www.pixiv.net/member.php?*
pixiv.vbs|vbscript|UTF-8|photo|http://www.pixiv.net/member_illust.php?*
pixiv.vbs|vbscript|UTF-8|photo|http://www.pixiv.net/tags.php?*
pixiv.vbs|vbscript|UTF-8|photo|http://www.pixiv.net/search.php?*
pixiv.vbs|vbscript|UTF-8|album|http://www.pixiv.net/bookmark.php?type=user*
pixiv.vbs|vbscript|UTF-8|album|http://www.pixiv.net/bookmark.php?type=reg_user*
pixiv.vbs|vbscript|UTF-8|photo|http://www.pixiv.net/bookmark.php*
pixiv.vbs|vbscript|UTF-8|photo|http://www.pixiv.net/new_illust.php*
pixiv.vbs|vbscript|UTF-8|photo|http://www.pixiv.net/bookmark_new_illust*.php*
pixiv.vbs|vbscript|UTF-8|photo|http://www.pixiv.net/response.php?*
pixiv.vbs|vbscript|UTF-8|photo|http://www.pixiv.net/mypage.php
pixiv.vbs|vbscript|UTF-8|photo|http://www.pixiv.net/index.php
eht.vbs|vbscript|UTF-8|album|http://g.e-hentai.org/g/?*/?*/*
eht.vbs|vbscript|UTF-8|photo|http://g.e-hentai.org/s/?*/?*-?*
eht.vbs|vbscript|UTF-8|album|http://exhentai.org/g/?*/?*/*
eht.vbs|vbscript|UTF-8|photo|http://exhentai.org/s/?*/?*-?*
konachan.vbs|vbscript|UTF-8|photo|http://konachan.com/*
gelbr.vbs|vbscript|UTF-8|photo|http://gelbooru.com/*
gelbr.vbs|vbscript|UTF-8|photo|http://www.gelbooru.com/*
gelbr.vbs|vbscript|UTF-8|photo|http://youhate.us/*
gelbr.vbs|vbscript|UTF-8|photo|http://www.youhate.us/*
picasa.vbs|vbscript|UTF-8|photo|http://picasaweb.google.*/?*/?*
picasa.vbs|vbscript|UTF-8|photo|https://picasaweb.google.*/?*/?*
picasa.vbs|vbscript|UTF-8|album|http://picasaweb.google.*/?*
picasa.vbs|vbscript|UTF-8|album|https://picasaweb.google.*/?*
behoimi.vbs|vbscript|UTF-8|photo|http://behoimi.org/*
behoimi.vbs|vbscript|UTF-8|photo|http://www.behoimi.org/*
yupoo.vbs|vbscript|UTF-8|photo|http://v.yupoo.com/?*/view?*
yupoo.vbs|vbscript|UTF-8|album|http://?*.yupoo.com*
apple.vbs|vbscript|UTF-8|photo|http://?*.apple.com/trailers/*
sohu.vbs|vbscript|GB2312|photo|http://pp.sohu.com/photo?*
sohu.vbs|vbscript|GB2312|album|http://pp.sohu.com/user/?*/*
sohu.vbs|vbscript|GB2312|album|http://pp.sohu.com/member/*
sohu.vbs|vbscript|GB2312|album|http://pp.sohu.com/setlist.jhtml?*
sohu.vbs|vbscript|GB2312|photo|http://?*.blog.sohu.com/album/photo?*
sohu.vbs|vbscript|GB2312|album|http://?*.blog.sohu.com*
sankakucomplex.vbs|vbscript|UTF-8|photo|http://*.sankakucomplex.com*
wallcoo.vbs|vbscript|GB2312|photo|http://www.wallcoo.com/?*/?*/?*
photobucket.vbs|vbscript|UTF-8|photo|http://photobucket.com*
photobucket.vbs|vbscript|UTF-8|photo|http://*.photobucket.com*
yahoo.vbs|vbscript|UTF-8|photo|http://photos.i.cn.yahoo.com/?*/?*/*
yahoo.vbs|vbscript|UTF-8|album|http://photos.i.cn.yahoo.com/?*/*
yxnpc.vbs|vbscript|GB2312|photo|http://www.yxnpc.com/?*-?*-?*/?*/?*.html*
yxnpc.vbs|vbscript|GB2312|album|http://www.yxnpc.com/manhua/?*
booru.vbs|vbscript|UTF-8|photo|http://?*.booru.org/*
b-sys.vbs|vbscript|UTF-8|photo|http://safebooru.org/*
b-sys.vbs|vbscript|UTF-8|photo|http://lolibooru.com/*
b-sys.vbs|vbscript|UTF-8|photo|b http://?*
douban.vbs|vbscript|UTF-8|photo|http://www.douban.com/photos/?*
douban.vbs|vbscript|UTF-8|album|http://www.douban.com/people/?*